apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: graphql-starter
  title: GraphQL Service
  description: |
    A GraphQL starter template for backstage to get you up and running
    the best pracices with GraphQL
spec:
  type: cookiecutter
