apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: graphql-starter
  title: GraphQL Service
  tags:
    - Experimental
    - GraphQL
    - React
  description: |
    A GraphQL starter template for backstage to get you up and running
    the best pracices with GraphQL
spec:
  type: service
  processor: cookiecutter
  path: './template'
